import hashlib
import random
import string

BASE_URL = "http://127.0.0.1:5000"


def gen_random_string(str_len):
    '''
    randomly create a string, consisting of numbers and letters, 
    with a length of str_len
    '''

    return ''.join(
        random.choice(string.ascii_letters + string.digits)
        for _ in range(str_len))


def gen_md5(*args):
    '''
    return the hexdigest format of the MD5 code generated by *args
    '''

    return hashlib.md5(''.join(args).encode('utf-8')).hexdigest()


def is_status_code_200(status_code):
    return status_code == 200
